using FluentValidation;
namespace AiVideoStudio.Application.Features.Workflows.Validators;
public sealed class StepDefinitionValidator:AbstractValidator<DTOs.WorkflowStepDefinition>{public StepDefinitionValidator(){RuleFor(x=>x.Name).NotEmpty().MaximumLength(200);RuleFor(x=>x.Type).IsInEnum();RuleFor(x=>x.TimeoutSeconds).InclusiveBetween(1,3600);RuleFor(x=>x.MaxRetries).InclusiveBetween(0,10);}}
public sealed class CreateWorkflowValidator:AbstractValidator<CreateWorkflowCommand>{public CreateWorkflowValidator(){RuleFor(x=>x.ProjectId).NotEmpty();RuleFor(x=>x.Name).NotEmpty().MaximumLength(200);RuleFor(x=>x.Steps).NotEmpty();RuleForEach(x=>x.Steps).SetValidator(new StepDefinitionValidator());}}
public sealed class UpdateWorkflowValidator:AbstractValidator<UpdateWorkflowCommand>{public UpdateWorkflowValidator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Name).NotEmpty();RuleForEach(x=>x.Steps).SetValidator(new StepDefinitionValidator());}}
public class WorkflowIdValidator<T>:AbstractValidator<T>{public WorkflowIdValidator(Func<T,string> id)=>RuleFor(x=>id(x)).NotEmpty();}
public sealed class RunWorkflowValidator:WorkflowIdValidator<RunWorkflowCommand>{public RunWorkflowValidator():base(x=>x.Id){}}public sealed class CancelWorkflowValidator:WorkflowIdValidator<CancelWorkflowCommand>{public CancelWorkflowValidator():base(x=>x.Id){}}public sealed class RetryWorkflowValidator:WorkflowIdValidator<RetryWorkflowCommand>{public RetryWorkflowValidator():base(x=>x.Id){}}public sealed class PauseWorkflowValidator:WorkflowIdValidator<PauseWorkflowCommand>{public PauseWorkflowValidator():base(x=>x.Id){}}public sealed class ResumeWorkflowValidator:WorkflowIdValidator<ResumeWorkflowCommand>{public ResumeWorkflowValidator():base(x=>x.Id){}}
public sealed class DeleteWorkflowValidator:WorkflowIdValidator<DeleteWorkflowCommand>{public DeleteWorkflowValidator():base(x=>x.Id){}}
public sealed class UpdateWorkflowVariablesValidator:WorkflowIdValidator<UpdateWorkflowVariablesCommand>{public UpdateWorkflowVariablesValidator():base(x=>x.Id){RuleFor(x=>x.Variables).NotNull();}}
public sealed class GetWorkflowByIdValidator:WorkflowIdValidator<GetWorkflowByIdQuery>{public GetWorkflowByIdValidator():base(x=>x.Id){}}
public sealed class GetWorkflowExecutionValidator:AbstractValidator<GetWorkflowExecutionQuery>{public GetWorkflowExecutionValidator(){RuleFor(x=>x.WorkflowId).NotEmpty();}}
public sealed class GetProjectWorkflowsValidator:AbstractValidator<GetProjectWorkflowsQuery>{public GetProjectWorkflowsValidator(){RuleFor(x=>x.ProjectId).NotEmpty();RuleFor(x=>x.Page).GreaterThan(0);RuleFor(x=>x.PageSize).InclusiveBetween(1,100);}}
