using AiVideoStudio.Domain.Base;using AiVideoStudio.Domain.Enums;using AiVideoStudio.Domain.Events.Workflows;
namespace AiVideoStudio.Domain.Entities;
public sealed class AIWorkflow:BaseEntity
{
    private readonly List<WorkflowStep> _steps=new();private readonly List<WorkflowVariable> _variables=new();
    public string ProjectId{get;private set;}=string.Empty;public string OwnerId{get;private set;}=string.Empty;public string Name{get;private set;}=string.Empty;public string? Description{get;private set;}
    public WorkflowStatus Status{get;private set;}public bool IsPaused{get;private set;}public int Version{get;private set;}public string? CurrentExecutionId{get;private set;}public string? Error{get;private set;}
    public IReadOnlyCollection<WorkflowStep> Steps=>_steps.AsReadOnly();public IReadOnlyCollection<WorkflowVariable> Variables=>_variables.AsReadOnly();public bool IsDeleted=>DeletedAt.HasValue;
    private AIWorkflow(){}
    public static AIWorkflow Create(string projectId,string ownerId,string name,string? description,IEnumerable<WorkflowStep> steps,IEnumerable<WorkflowVariable>? variables=null)
    {if(string.IsNullOrWhiteSpace(projectId)||string.IsNullOrWhiteSpace(ownerId)||string.IsNullOrWhiteSpace(name))throw new ArgumentException();var w=new AIWorkflow{ProjectId=projectId,OwnerId=ownerId,Name=name,Description=description,Status=WorkflowStatus.Draft,Version=1,CreatedAt=DateTimeOffset.UtcNow,CreatedBy=ownerId};w._steps.AddRange(steps);w._variables.AddRange(variables??Array.Empty<WorkflowVariable>());w.ValidateDag();w.Status=WorkflowStatus.Ready;w.AddDomainEvent(new WorkflowCreatedEvent(w.Id,ownerId));return w;}
    public void Update(string name,string? description,IEnumerable<WorkflowStep> steps){if(Status==WorkflowStatus.Running)throw new InvalidOperationException();Name=name;Description=description;_steps.Clear();_steps.AddRange(steps);ValidateDag();Status=WorkflowStatus.Ready;Touch();}
    public void UpdateVariables(IDictionary<string,string> values){foreach(var pair in values){var v=_variables.FirstOrDefault(x=>x.Name==pair.Key);if(v is null)_variables.Add(new(pair.Key,pair.Value));else v.Set(pair.Value);}Touch();}
    public void Start(string executionId){if(Status!=WorkflowStatus.Ready)throw new InvalidOperationException();CurrentExecutionId=executionId;Status=WorkflowStatus.Running;IsPaused=false;Error=null;Touch();AddDomainEvent(new WorkflowStartedEvent(Id,executionId));}
    public void Pause(){if(Status!=WorkflowStatus.Running||IsPaused)throw new InvalidOperationException();IsPaused=true;Touch();}public void Resume(){if(Status!=WorkflowStatus.Running||!IsPaused)throw new InvalidOperationException();IsPaused=false;Touch();}
    public void StepStarted(string id){AddDomainEvent(new WorkflowStepStartedEvent(Id,id));Touch();}public void StepCompleted(string id){AddDomainEvent(new WorkflowStepCompletedEvent(Id,id));Touch();}public void StepFailed(string id,string error){AddDomainEvent(new WorkflowStepFailedEvent(Id,id,error));Touch();}
    public void Complete(){if(Status!=WorkflowStatus.Running||_steps.Any(s=>s.Status is not(WorkflowStepStatus.Completed or WorkflowStepStatus.Skipped)))throw new InvalidOperationException();Status=WorkflowStatus.Completed;Touch();AddDomainEvent(new WorkflowCompletedEvent(Id));}
    public void Fail(string error){if(Status!=WorkflowStatus.Running)throw new InvalidOperationException();Status=WorkflowStatus.Failed;Error=error;Touch();}
    public void Cancel(){if(Status is WorkflowStatus.Completed or WorkflowStatus.Cancelled)throw new InvalidOperationException();Status=WorkflowStatus.Cancelled;IsPaused=false;foreach(var s in _steps)s.Cancel();Touch();AddDomainEvent(new WorkflowCancelledEvent(Id));}
    public void Retry(){if(Status!=WorkflowStatus.Failed)throw new InvalidOperationException();foreach(var s in _steps.Where(x=>x.Status is WorkflowStepStatus.Failed or WorkflowStepStatus.Cancelled))s.Reset();Status=WorkflowStatus.Ready;Error=null;Touch();AddDomainEvent(new WorkflowRetriedEvent(Id));}
    public void SoftDelete(){if(Status==WorkflowStatus.Running)throw new InvalidOperationException();DeletedAt=DateTimeOffset.UtcNow;DeletedBy=OwnerId;Touch();}
    public void ValidateDag(){var ids=_steps.Select(x=>x.Id).ToHashSet();if(ids.Count!=_steps.Count)throw new InvalidOperationException("Duplicate step id.");if(_steps.SelectMany(x=>x.Dependencies).Any(d=>!ids.Contains(d)))throw new InvalidOperationException("Unknown dependency.");var visiting=new HashSet<string>();var visited=new HashSet<string>();bool Visit(string id){if(visiting.Contains(id))return false;if(visited.Contains(id))return true;visiting.Add(id);foreach(var d in _steps.Single(x=>x.Id==id).Dependencies)if(!Visit(d))return false;visiting.Remove(id);visited.Add(id);return true;}if(_steps.Any(s=>!Visit(s.Id)))throw new InvalidOperationException("Workflow graph must be acyclic.");}
    private void Touch(){Version++;UpdatedAt=DateTimeOffset.UtcNow;UpdatedBy=OwnerId;}
}
