using System.Net;using System.Net.Http.Json;using AiVideoStudio.Api.Controllers.v1;using AiVideoStudio.Application.Interfaces.Operations;using AiVideoStudio.Domain.Entities;using AiVideoStudio.Domain.Enums;using AiVideoStudio.Shared.Responses;using FluentAssertions;using NSubstitute;using Xunit;
namespace AiVideoStudio.IntegrationTests.Controllers;
public sealed class OperationsControllerIntegrationTests:IClassFixture<CustomWebApplicationFactory>
{private readonly CustomWebApplicationFactory _f;private readonly HttpClient _c;public OperationsControllerIntegrationTests(CustomWebApplicationFactory f){_f=f;_c=f.CreateClient();f.CurrentUser.IsAuthenticated.Returns(true);f.CurrentUser.UserId.Returns("admin");f.CurrentUser.Roles.Returns(["Admin"]);f.HealthCheckService.CheckAsync(Arg.Any<bool>(),Arg.Any<CancellationToken>()).Returns(x=>new SystemHealth(true,DateTimeOffset.UtcNow,[new("process",true)]));}
[Fact]public async Task Health_returns_ok(){(await _c.GetAsync("/api/v1/system/health")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Ready_returns_ok(){(await _c.GetAsync("/api/v1/system/ready")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Live_returns_security_and_correlation_headers(){var r=await _c.GetAsync("/api/v1/system/live");r.StatusCode.Should().Be(HttpStatusCode.OK);r.Headers.Contains("X-Correlation-Id").Should().BeTrue();r.Headers.Contains("X-Request-Id").Should().BeTrue();r.Headers.Contains("X-Content-Type-Options").Should().BeTrue();}
[Fact]public async Task Configuration_get_returns_ok(){_f.SystemConfigurationRepository.GetAllAsync(Arg.Any<CancellationToken>()).Returns(Array.Empty<SystemConfiguration>());(await _c.GetAsync("/api/v1/system/configuration")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Configuration_put_upserts(){SystemConfiguration? saved=null;_f.SystemConfigurationRepository.When(x=>x.UpsertAsync(Arg.Any<SystemConfiguration>(),Arg.Any<CancellationToken>())).Do(x=>saved=x.Arg<SystemConfiguration>());var r=await _c.PutAsJsonAsync("/api/v1/system/configuration",new UpdateConfigurationRequest{Key="feature",Value="on"});r.StatusCode.Should().Be(HttpStatusCode.OK);saved.Should().NotBeNull();}
[Fact]public async Task Metrics_returns_ok(){(await _c.GetAsync("/api/v1/system/metrics")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Audit_returns_page(){_f.AuditLogRepository.GetPagedAsync(1,20,Arg.Any<CancellationToken>()).Returns(new PagedResult<AuditLog>([],0,1,20));(await _c.GetAsync("/api/v1/system/audit")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Notifications_return_owner_page(){_f.NotificationRepository.GetByUserAsync("admin",1,20,Arg.Any<CancellationToken>()).Returns(new PagedResult<SystemNotification>([],0,1,20));(await _c.GetAsync("/api/v1/system/notifications")).StatusCode.Should().Be(HttpStatusCode.OK);}
[Fact]public async Task Maintenance_returns_accepted(){_f.MaintenanceRunner.RunAsync("retention","admin",Arg.Any<CancellationToken>()).Returns(MaintenanceTask.Create("retention","admin"));var r=await _c.PostAsJsonAsync("/api/v1/system/maintenance",new RunMaintenanceRequest{Name="retention"});r.StatusCode.Should().Be(HttpStatusCode.Accepted);}
}
