using AiVideoStudio.Application.Configuration;using AiVideoStudio.Application.Features.Operations;using AiVideoStudio.Application.Features.Operations.Validators;using AiVideoStudio.Application.Interfaces.Operations;using AiVideoStudio.Domain.Entities;using AiVideoStudio.Domain.Enums;using AiVideoStudio.Domain.Events.Operations;using AiVideoStudio.Infrastructure.Mongo.Repositories;using AiVideoStudio.Infrastructure.Operations;using AiVideoStudio.Infrastructure.Persistence.Repositories;using FluentAssertions;using Microsoft.AspNetCore.Http;using Microsoft.Extensions.Options;using MongoDB.Driver;using NSubstitute;using Xunit;
namespace AiVideoStudio.UnitTests.Operations;
public sealed class OperationsFoundationTests
{
    [Fact]public void Notification_can_be_marked_read(){var n=SystemNotification.Create("u","title","message",NotificationType.Information);n.IsRead.Should().BeFalse();n.MarkRead();n.IsRead.Should().BeTrue();n.DomainEvents.Should().ContainSingle(x=>x is NotificationCreatedEvent);}
    [Fact]public void Quota_emits_event_when_exceeded(){var q=UserQuota.Create("u",QuotaType.ApiRequests,2);q.Record(3).Should().BeFalse();q.DomainEvents.Should().ContainSingle(x=>x is QuotaExceededEvent);}
    [Fact]public void Configuration_updates_value_and_audit_fields(){var c=SystemConfiguration.Create("feature","off");c.Update("on","admin");c.Value.Should().Be("on");c.UpdatedBy.Should().Be("admin");}
    [Fact]public void Maintenance_tracks_lifecycle(){var m=MaintenanceTask.Create("cleanup","admin");m.Start();m.Complete(7);m.Status.Should().Be(MaintenanceStatus.Completed);m.DeletedRecords.Should().Be(7);m.DomainEvents.Should().HaveCount(2);}
    [Fact]public void Metrics_tracks_counters_gauges_and_average(){var m=new MetricsCollector();m.Increment("requests",2);m.SetGauge("queue",3);m.Observe("latency",TimeSpan.FromMilliseconds(10));m.Observe("latency",TimeSpan.FromMilliseconds(30));var s=m.Snapshot();s["requests"].Should().Be(2);s["queue"].Should().Be(3);s["latency.average_ms"].Should().Be(20);}
    [Fact]public void Rate_limiter_enforces_configured_window(){var limiter=new FixedWindowRateLimiter(Options.Create(new SystemOptions{SigningKey="01234567890123456789012345678901",RateLimitPermitCount=2,RateLimitWindowSeconds=60}));limiter.TryAcquire("u").Should().BeTrue();limiter.TryAcquire("u").Should().BeTrue();limiter.TryAcquire("u").Should().BeFalse();}
    [Fact]public void Signed_url_round_trip_is_valid(){var service=new SignedUrlService(Options.Create(new SystemOptions{SigningKey="01234567890123456789012345678901"}));var signed=service.Sign(new Uri("https://assets.test/video.mp4"),TimeSpan.FromMinutes(1));service.Validate(signed).Should().BeTrue();signed.Query.Should().Contain("signature=");}
    [Fact]public void Request_context_reads_correlation_request_user_and_ip(){var context=new DefaultHttpContext();context.TraceIdentifier="request-1";context.Items["X-Correlation-Id"]="correlation-1";context.User=new System.Security.Claims.ClaimsPrincipal(new System.Security.Claims.ClaimsIdentity([new("userId","u")],"test"));var service=new RequestContext(new HttpContextAccessor{HttpContext=context});service.RequestId.Should().Be("request-1");service.CorrelationId.Should().Be("correlation-1");service.UserId.Should().Be("u");}
    [Fact]public void Notification_validator_rejects_empty_message(){new CreateNotificationValidator().Validate(new CreateNotificationCommand("u","title","",NotificationType.Information)).IsValid.Should().BeFalse();}
    [Fact]public void Usage_validator_rejects_non_positive_amount(){new RecordUsageValidator().Validate(new RecordUsageCommand(QuotaType.ApiRequests,0,"r")).IsValid.Should().BeFalse();}
    [Fact]public async Task Notification_repository_inserts(){var c=Substitute.For<IMongoCollection<SystemNotification>>();var n=SystemNotification.Create("u","t","m",NotificationType.Information);await new NotificationRepository(c).AddAsync(n);await c.Received().InsertOneAsync(n,Arg.Any<InsertOneOptions>(),Arg.Any<CancellationToken>());}
    [Fact]public async Task Quota_repository_inserts_usage(){var quotas=Substitute.For<IMongoCollection<UserQuota>>();var usage=Substitute.For<IMongoCollection<UsageRecord>>();var record=UsageRecord.Create("u",QuotaType.ApiRequests,1,"r");await new QuotaRepository(quotas,usage).AddUsageAsync(record);await usage.Received().InsertOneAsync(record,Arg.Any<InsertOneOptions>(),Arg.Any<CancellationToken>());}
    [Fact]public async Task Configuration_repository_upserts(){var c=Substitute.For<IMongoCollection<SystemConfiguration>>();var item=SystemConfiguration.Create("key","value");await new SystemConfigurationRepository(c).UpsertAsync(item);await c.Received().ReplaceOneAsync(Arg.Any<FilterDefinition<SystemConfiguration>>(),item,Arg.Is<ReplaceOptions>(x=>x.IsUpsert),Arg.Any<CancellationToken>());}
    [Fact]public async Task Maintenance_repository_inserts(){var c=Substitute.For<IMongoCollection<MaintenanceTask>>();var item=MaintenanceTask.Create("cleanup","admin");await new MaintenanceRepository(c).AddAsync(item);await c.Received().InsertOneAsync(item,Arg.Any<InsertOneOptions>(),Arg.Any<CancellationToken>());}
    [Fact]public async Task Audit_repository_inserts(){var c=Substitute.For<IMongoCollection<AuditLog>>();var item=new AuditLog{UserId="u",Action="Read"};await new AuditLogRepository(c).AddAsync(item);await c.Received().InsertOneAsync(item,Arg.Any<InsertOneOptions>(),Arg.Any<CancellationToken>());}
    [Fact]public async Task Notification_dispatcher_persists_and_counts(){var repo=Substitute.For<AiVideoStudio.Domain.Interfaces.INotificationRepository>();var metrics=new MetricsCollector();var n=await new NotificationDispatcher(repo,metrics).DispatchAsync("u","t","m",NotificationType.Success);await repo.Received().AddAsync(n,Arg.Any<CancellationToken>());metrics.Snapshot()["notifications.dispatched"].Should().Be(1);}
}
