using AiVideoStudio.Application.Features.Operations.DTOs;using AiVideoStudio.Application.Interfaces;using AiVideoStudio.Application.Interfaces.Operations;using AiVideoStudio.Domain.Entities;using AiVideoStudio.Domain.Interfaces;using AiVideoStudio.Shared.DomainErrors;using AiVideoStudio.Shared.Responses;using AutoMapper;using MediatR;
namespace AiVideoStudio.Application.Features.Operations.Handlers;
public sealed class OperationCommandHandlers:IRequestHandler<CreateNotificationCommand,Result<NotificationDto>>,IRequestHandler<MarkNotificationReadCommand,Result>,IRequestHandler<UpdateSystemConfigurationCommand,Result<ConfigurationDto>>,IRequestHandler<RecordUsageCommand,Result<UsageDto>>,IRequestHandler<RunMaintenanceCommand,Result<MaintenanceDto>>
{private readonly INotificationRepository _notifications;private readonly ISystemConfigurationRepository _configuration;private readonly IQuotaRepository _quotas;private readonly INotificationDispatcher _dispatcher;private readonly IMaintenanceRunner _maintenance;private readonly ICurrentUser _user;private readonly IMapper _mapper;
public OperationCommandHandlers(INotificationRepository n,ISystemConfigurationRepository c,IQuotaRepository q,INotificationDispatcher d,IMaintenanceRunner m,ICurrentUser u,IMapper map){_notifications=n;_configuration=c;_quotas=q;_dispatcher=d;_maintenance=m;_user=u;_mapper=map;}
public async Task<Result<NotificationDto>> Handle(CreateNotificationCommand q,CancellationToken ct){if(!Authenticated())return Result<NotificationDto>.Failure(OperationsErrors.Unauthorized);if(q.UserId!=_user.UserId&&!Admin())return Result<NotificationDto>.Failure(OperationsErrors.Forbidden);var n=await _dispatcher.DispatchAsync(q.UserId,q.Title,q.Message,q.Type,ct);return Result<NotificationDto>.Success(_mapper.Map<NotificationDto>(n));}
public async Task<Result> Handle(MarkNotificationReadCommand q,CancellationToken ct){var n=await _notifications.GetAsync(q.Id,ct);if(n is null)return Result.Failure(OperationsErrors.NotFound);if(!Authenticated())return Result.Failure(OperationsErrors.Unauthorized);if(n.UserId!=_user.UserId&&!Admin())return Result.Failure(OperationsErrors.Forbidden);n.MarkRead();await _notifications.UpdateAsync(n,ct);return Result.Success();}
public async Task<Result<ConfigurationDto>> Handle(UpdateSystemConfigurationCommand q,CancellationToken ct){if(!Admin())return Result<ConfigurationDto>.Failure(OperationsErrors.Forbidden);var item=await _configuration.GetAsync(q.Key,ct)??SystemConfiguration.Create(q.Key,q.Value,q.IsSensitive);if(item.Value!=q.Value)item.Update(q.Value,_user.UserId!);await _configuration.UpsertAsync(item,ct);return Result<ConfigurationDto>.Success(_mapper.Map<ConfigurationDto>(item));}
public async Task<Result<UsageDto>> Handle(RecordUsageCommand q,CancellationToken ct){if(!Authenticated())return Result<UsageDto>.Failure(OperationsErrors.Unauthorized);var usage=UsageRecord.Create(_user.UserId!,q.Type,q.Amount,q.ResourceId);await _quotas.AddUsageAsync(usage,ct);var quota=await _quotas.GetAsync(_user.UserId!,q.Type,ct);if(quota is not null){var allowed=quota.Record(q.Amount);await _quotas.UpsertAsync(quota,ct);if(!allowed)return Result<UsageDto>.Failure(OperationsErrors.QuotaExceeded);}return Result<UsageDto>.Success(_mapper.Map<UsageDto>(usage));}
public async Task<Result<MaintenanceDto>> Handle(RunMaintenanceCommand q,CancellationToken ct){if(!Admin())return Result<MaintenanceDto>.Failure(OperationsErrors.Forbidden);var task=await _maintenance.RunAsync(q.Name,_user.UserId!,ct);return Result<MaintenanceDto>.Success(_mapper.Map<MaintenanceDto>(task));}
private bool Authenticated()=>_user.IsAuthenticated&&!string.IsNullOrWhiteSpace(_user.UserId);private bool Admin()=>Authenticated()&&(_user.Roles.Contains("Admin")||_user.Roles.Contains("Administrator"));}
public sealed class OperationQueryHandlers:IRequestHandler<GetNotificationsQuery,Result<PagedResult<NotificationDto>>>,IRequestHandler<GetAuditLogsQuery,Result<PagedResult<AuditLogDto>>>,IRequestHandler<GetQuotaQuery,Result<QuotaDto>>,IRequestHandler<GetSystemConfigurationQuery,Result<IReadOnlyList<ConfigurationDto>>>
{private readonly INotificationRepository _n;private readonly IAuditLogRepository _a;private readonly IQuotaRepository _q;private readonly ISystemConfigurationRepository _c;private readonly ICurrentUser _u;private readonly IMapper _m;public OperationQueryHandlers(INotificationRepository n,IAuditLogRepository a,IQuotaRepository q,ISystemConfigurationRepository c,ICurrentUser u,IMapper m){_n=n;_a=a;_q=q;_c=c;_u=u;_m=m;}
public async Task<Result<PagedResult<NotificationDto>>> Handle(GetNotificationsQuery x,CancellationToken ct){if(!Auth())return Result<PagedResult<NotificationDto>>.Failure(OperationsErrors.Unauthorized);var p=await _n.GetByUserAsync(_u.UserId!,x.Page,x.PageSize,ct);return Result<PagedResult<NotificationDto>>.Success(new(p.Items.Select(_m.Map<NotificationDto>).ToList(),p.TotalCount,p.Page,p.PageSize));}
public async Task<Result<PagedResult<AuditLogDto>>> Handle(GetAuditLogsQuery x,CancellationToken ct){if(!Admin())return Result<PagedResult<AuditLogDto>>.Failure(OperationsErrors.Forbidden);var p=await _a.GetPagedAsync(x.Page,x.PageSize,ct);return Result<PagedResult<AuditLogDto>>.Success(new(p.Items.Select(_m.Map<AuditLogDto>).ToList(),p.TotalCount,p.Page,p.PageSize));}
public async Task<Result<QuotaDto>> Handle(GetQuotaQuery x,CancellationToken ct){if(!Auth())return Result<QuotaDto>.Failure(OperationsErrors.Unauthorized);var q=await _q.GetAsync(_u.UserId!,x.Type,ct);return q is null?Result<QuotaDto>.Failure(OperationsErrors.NotFound):Result<QuotaDto>.Success(_m.Map<QuotaDto>(q));}
public async Task<Result<IReadOnlyList<ConfigurationDto>>> Handle(GetSystemConfigurationQuery x,CancellationToken ct){if(!Admin())return Result<IReadOnlyList<ConfigurationDto>>.Failure(OperationsErrors.Forbidden);var values=await _c.GetAllAsync(ct);return Result<IReadOnlyList<ConfigurationDto>>.Success(values.Select(_m.Map<ConfigurationDto>).ToList());}
private bool Auth()=>_u.IsAuthenticated&&!string.IsNullOrWhiteSpace(_u.UserId);private bool Admin()=>Auth()&&(_u.Roles.Contains("Admin")||_u.Roles.Contains("Administrator"));}
